language: node_js
sudo: false
node_js:
  - "7"
  - "8"
install:
  - npm install
before_script:
  - npm install -g jshint
services:
  - mongodb
cache:
  directories:
    - "node_modules"
script:
  - jshint .
  - npm test
  - npm run test-with-coverage